### ISSUE TITLE
68:undefined method `each' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by gfxgoat** [pjmuller/zendesk-helpcenter-export#5]
Hi when running the script i get the following error: 
ruby zendesk-helpcenter-export.rb xxx@xxx.zendesk.com xpassx xdomainx verbose

zendesk-helpcenter-export.rb:68:in `to_html!': undefined method`each' for nil:NilClass (NoMethodError)
from zendesk-helpcenter-export.rb:230:in `<main>'

i get the same error if i add the verbose command

what am i doing wrong ?

thanks
Gordon

**Comment by megajustice** [comment]
I'm having this issue as well. What can we do?

**Comment by megajustice** [comment]
Bump?! Please help.

**Comment by megajustice** [comment]
By the way, we are running ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]

**Comment by pjmuller** [comment]
Hi @megajustice and @gfxgoat , sorry that it took so long to reply. Health issues in the family...

iit seems that the API call is not returning any categories, on closer inspection this is 99% sure because of incorrect connection data. I added clearer debugging in pull request #8 

This will tell you more about why the API call failed. Can you try it and (try to change your login credentials?) and see if it then works?

**Comment by gfxgoat** [comment]
thanks I will give it a shot

**Comment by pjmuller** [comment]
@gfxgoat , did it fix it? So that I know if I can close this issue?
@megajustice did you try it again?
